HISTFILE=$HOME/.local/share/zsh/history
HISTSIZE=11000
SAVEHIST=10000
HIST_STAMPS=yyyy-mm-dd

setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
